export default {
    case1: {
        test: 'Return 20 episodes in case of more then 20 episodes',
        tvDetails: {
            seasons: [
                {season_number: 1},
                {season_number: 2},
                {season_number: 3},
            ],
        },
        seasonsDetails: [
            { episodes: [
                    {name: 'Disaster', vote_average: 7},
                    {name: 'Debts', vote_average: 5.5},
                    {name: 'Claire', vote_average: 5},
                    {name: 'Take My Hand', vote_average: 5},
                    {name: 'First Case, Second Base', vote_average: 5},
                    {name: '45-Degree Angle', vote_average: 5.5},
                    {name: 'SFAD', vote_average: 6},
                    {name: 'Moonshot', vote_average: 4.5},
                    {name: 'Incomplete', vote_average: 5},
                    {name: 'Friends and Family', vote_average: 5.25},
                    {name: 'Fractured', vote_average: 8},
                    {name: 'Mutations', vote_average: 9},
                    {name: 'Sex and Death', vote_average: 8},
                    {name: 'Influence', vote_average: 8},
                    {name: 'Unsaid', vote_average: 8},
                    {name: 'Autopsy', vote_average: 8},
                    {name: 'Fixation', vote_average: 9},
                    {name: 'Heartbreak', vote_average: 8},
                    {name: 'Hurt (1)', vote_average: 8},
                    {name: 'I Love You (2)', vote_average: 8}
                ],
            },
            {
                episodes: [
                    {name: 'Hello', vote_average: 6.444},
                    {name: 'Middle Ground', vote_average: 7.286},
                    {name: '36 Hours', vote_average: 7.143},
                    {name: 'Tough Titmouse', vote_average: 7.2},
                    {name: 'Carrots', vote_average: 7},
                    {name: 'Two-Ply (or Not Two-Ply)', vote_average: 6.5},
                    {name: 'Hubert', vote_average: 6.5},
                    {name: 'Stories', vote_average: 7},
                    {name: 'Empathy', vote_average: 6.25},
                    {name: 'Quarantine (1)', vote_average: 7.4},
                    {name: 'Quarantine Part Two (2)', vote_average: 6.4},
                    {name: 'Aftermath', vote_average: 8},
                    {name: 'Xin', vote_average: 6},
                    {name: 'Faces', vote_average: 7.667},
                    {name: 'Risk and Reward', vote_average: 7.2},
                    {name: 'Believe', vote_average: 6.25},
                    {name: 'Breakdown', vote_average: 7},
                    {name: 'Trampoline', vote_average: 6.25}
                ],
            },
            { episodes: [
                    {name: 'Burnt Food', vote_average: 6.793 },
                    {name: 'Mount Rushmore', vote_average: 7.8 },
                    {name: 'Oliver', vote_average: 7.6 },
                    {name: 'Pipes', vote_average: 7.556 },
                    {name: 'Point Three Percent', vote_average: 7.1 },
                    {name: 'Not Fake', vote_average: 7.556 },
                    {name: '22 Steps', vote_average: 7.375 },
                    {name: 'Apple', vote_average: 8.143 },
                    {name: 'Intangibles', vote_average: 7.25 },
                    {name: 'Sacrifice', vote_average: 7.333 },
                    {name: 'Islands Part One (1)', vote_average: 7.222 },
                    {name: 'Islands Part Two (2)', vote_average: 7.714 },
                    {name: 'Seven Reasons', vote_average: 7.375 },
                    {name: 'She', vote_average: 7.333 },
                    {name: 'Heartfelt', vote_average: 7 },
                    {name: 'Pain', vote_average: 7.167 },
                    {name: 'Smile', vote_average: 7.5 },
                    {name: 'More', vote_average: 8.143 }
                ],
            },
        ],
        result: {
            episodes: [
                { episodeName: 'Mutations', averageVotes: 9 },
                { episodeName: 'Fixation', averageVotes: 9 },
                { episodeName: 'More', averageVotes: 8.143 },
                { episodeName: 'Apple', averageVotes: 8.143 },
                { episodeName: 'Hurt (1)', averageVotes: 8 },
                { episodeName: 'Fractured', averageVotes: 8 },
                { episodeName: 'Sex and Death', averageVotes: 8 },
                { episodeName: 'Influence', averageVotes: 8 },
                { episodeName: 'Unsaid', averageVotes: 8 },
                { episodeName: 'Aftermath', averageVotes: 8 },
                { episodeName: 'Autopsy', averageVotes: 8 },
                { episodeName: 'Heartbreak', averageVotes: 8 },
                { episodeName: 'I Love You (2)', averageVotes: 8 },
                { episodeName: 'Mount Rushmore', averageVotes: 7.8 },
                { episodeName: 'Islands Part Two (2)', averageVotes: 7.714 },
                { episodeName: 'Faces', averageVotes: 7.667 },
                { episodeName: 'Oliver', averageVotes: 7.6 },
                { episodeName: 'Pipes', averageVotes: 7.556 },
                { episodeName: 'Not Fake', averageVotes: 7.556 },
                { episodeName: 'Smile', averageVotes: 7.5 }
            ],
        },
        seriesId: '71712',
    },
    case2: {
        test: 'Return less then 20 episodes in case of less then 20 episodes',
        tvDetails: {
            seasons: [
                { season_number: 1 },
            ],
        },
        seasonsDetails: [
            {
                episodes: [
                    {name: 'Sundown', vote_average: 8.571 },
                    {name: "Whitey's on the Moon", vote_average: 6 },
                    {name: 'Holy Ghost', vote_average: 6 },
                    {name: 'Jig-a-Bobo', vote_average: 0 },
                    {name: 'I Am.', vote_average: 0 },
                    {name: 'Meet Me in Daegu', vote_average: 0 },
                    {name: 'Strange Case', vote_average: 0 },
                    {name: 'A History of Violence', vote_average: 0 },
                    {name: 'Rewind 1921', vote_average: 0 },
                    {name: 'Full Circle', vote_average: 0 },

                ],
            },
        ],
        result: {
            episodes: [
                { episodeName: 'Sundown', averageVotes: 8.571 },
                { episodeName: "Whitey's on the Moon", averageVotes: 6 },
                { episodeName: 'Holy Ghost', averageVotes: 6 },
                { episodeName: 'Jig-a-Bobo', averageVotes: 0 },
                { episodeName: 'I Am.', averageVotes: 0 },
                { episodeName: 'Meet Me in Daegu', averageVotes: 0 },
                { episodeName: 'Strange Case', averageVotes: 0 },
                { episodeName: 'A History of Violence', averageVotes: 0 },
                { episodeName: 'Rewind 1921', averageVotes: 0 },
                { episodeName: 'Full Circle', averageVotes: 0 },
            ],
        },
        seriesId: '82816',
    },
}
